#!/bin/sh

# navigate to the directory where your script is located
cd ../../libs/node-tools/src/lib/update-last-modified

# run your script
ts-node update-last-modified.ts

# add changes made by the script to the commit
git add ./dev-blog/_posts

# exit with a zero status if everything is okay
exit 0